version: '3.1'
services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pet # Defina o nome do banco de dados
    ports:
      - "3306:3306"
    volumes:
      - pet_data:/var/lib/mysql

  backend:
    build: ./
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/pet
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  client:
    build:
      context: ./react-app/
      dockerfile: my-app/Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  pet_data:
